---
title: "viz"
author: "Steph Gad"
date: "April 16, 2016"
output: html_document
---

##Scatterplot

```{r load, results='hide', message=FALSE, warning=FALSE}
library(dplyr)
#install.packages("ggplot2")
library(ggplot2)
library(gapminder)

# preview data
gapminder

# get range of available data
summary(gapminder)

```


```{r}

# setup dataframe
g = gapminder %>%
  filter(year==2007) %>%   # most recent year 
  mutate(pop_m = pop/1e6)  # population, millions

# plot scatterplot of most recent year 
s = ggplot(g, aes(x=gdpPercap, y=lifeExp)) +
  geom_point()+
  geom_smooth()
s

# add aesthetic of size by population
s = s + 
  aes(size=pop_m)
s

# add aesthetic of color by continent
s = s + 
  aes(color=continent)
s

ggsave('hans.png') # to save to your current working directory 

# add title, update axes labels
s = s + 
  ggtitle('Health & Wealth of Nations for 2007') +
  xlab('GDP per capita ($/year)') +
  ylab('Life expectancy (years)')
s

# label legend
s = s + 
  scale_colour_discrete(name='Continent') +
  scale_size_continuous(name='Population (M)')
s

```

## Interactive 

```{r}
install.packages("plotly")
library(plotly) # install.packages('plotly')

# scatterplot (Note: key=country shows up on rollover)
s = ggplot(g, aes(x=gdpPercap, y=lifeExp, key=country)) +
  geom_point()
ggplotly(s)

```

## static maps
```{r}
install.packages(tmap)
library(tmap) # install.packages('tmap')

# load world spatial polygons
data(World)

# inspect values in World
World@data %>% tbl_df()

# gapminder countries not in World. skipping for now
g %>% 
  anti_join(World@data, by=c('country'='name')) %>% #rows that don't match
  arrange(desc(pop))

# World countries not in gapminder. skipping for now
World@data %>% 
  anti_join(g, by=c('name'='country')) %>% 
  arrange(desc(pop_est)) %>%
  select(iso_a3, name, pop_est)

# join gapminder data to World
World@data = World@data %>%
  left_join(g, by=c('name'='country')) #combines data sets 
```


```{r}
# make map
m = tm_shape(World) +
    tm_polygons('lifeExp', palette='RdYlGn', id='name', title='Life expectancy (years)', auto.palette.mapping=F) +
    tm_style_gray() + tm_format_World()
m

# show interactive map
tmap_leaflet(m)
```



